[package]
name = "rpncalc"
version = "0.1.0"
authors = ["sky0621 <sky14work@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
anyhow = "1.0.32"
thiserror = "1.0.20"
